# Introduction to Numpy

In [5]:
import numpy as np

## 1-D Array

In [12]:
lst=[1,2,3,5,8,11,22,88,45]
print(type(lst))
lst

<class 'list'>


[1, 2, 3, 5, 8, 11, 22, 88, 45]

In [15]:
np_lst = np.array(lst)
print(type(np_lst))
print(np_lst)

for i in np_lst:
    print(i)

<class 'numpy.ndarray'>
[ 1  2  3  5  8 11 22 88 45]
1
2
3
5
8
11
22
88
45


### insert value

In [18]:
n= np.insert(np_lst,3,90)
print(n)

[ 1  2  3 90  5  8 11 22 88 45]


### append value

In [27]:
n1 = np.append(n,[50,456,89])
print(n1)

[  1   2   3  90   5   8  11  22  88  45  50 456  89]


### delete value

In [36]:
n2 = np.delete(n1,9)
print(n2)

[  1   2   3  90   5   8  11  22  88  50 456  89]


### generate random number

In [51]:
rand = np.random.randint(0,50)
print(rand)

13


### create value in perticular range

In [138]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### find value

In [136]:
print(np_lst)
np.where(np_lst==88)


[ 1  2  3  5  8 11 22 88 45]


(array([7], dtype=int64),)

## 2D array

### shape, size

In [76]:
lst1 = [[1,2,3,45],
        [4,5,6,78],
        [7,8,9,56]]
#print(lst1)
nw_lst = np.array(lst1)
print(nw_lst)
print("Shape:",nw_lst.shape)
print("size:",nw_lst.size)


[[ 1  2  3 45]
 [ 4  5  6 78]
 [ 7  8  9 56]]
Shape: (3, 4)
size: 12


In [77]:
print(nw_lst[1:2,1:2])
print("____________")
print(nw_lst[:,1:])
print("____________")
print(nw_lst[:2,:2])
print("____________")
print(nw_lst[1:,1:])

[[5]]
____________
[[ 2  3 45]
 [ 5  6 78]
 [ 8  9 56]]
____________
[[1 2]
 [4 5]]
____________
[[ 5  6 78]
 [ 8  9 56]]


### reshape array

In [80]:
print(nw_lst)
nw_lst.reshape(4,3)

[[ 1  2  3 45]
 [ 4  5  6 78]
 [ 7  8  9 56]]


array([[ 1,  2,  3],
       [45,  4,  5],
       [ 6, 78,  7],
       [ 8,  9, 56]])

In [83]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
np.ones((4,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
np.ones((3,5),dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### array with random number

In [95]:
np.random.randint(0,50,(4,3))    #np.random.randint(range_start,range_stop,(shape_start,shape_stop))

array([[23, 13, 40],
       [36, 35, 46],
       [43,  1, 14],
       [11, 33, 25]])

In [101]:
np.append(nw_lst,[[100],[200],[300]],axis=1)

array([[  1,   2,   3,  45, 100],
       [  4,   5,   6,  78, 200],
       [  7,   8,   9,  56, 300]])

In [108]:
print(nw_lst)
np.append(nw_lst,[[100,200,300,400]],axis=0)

[[ 1  2  3 45]
 [ 4  5  6 78]
 [ 7  8  9 56]]


array([[  1,   2,   3,  45],
       [  4,   5,   6,  78],
       [  7,   8,   9,  56],
       [100, 200, 300, 400]])

In [115]:
print(nw_lst+2)
print("____________")
print(nw_lst-2)
print("____________")
print(nw_lst*2)
print("____________")
print(nw_lst/2)
print("____________")
print(nw_lst%2)

[[ 3  4  5 47]
 [ 6  7  8 80]
 [ 9 10 11 58]]
____________
[[-1  0  1 43]
 [ 2  3  4 76]
 [ 5  6  7 54]]
____________
[[  2   4   6  90]
 [  8  10  12 156]
 [ 14  16  18 112]]
____________
[[ 0.5  1.   1.5 22.5]
 [ 2.   2.5  3.  39. ]
 [ 3.5  4.   4.5 28. ]]
____________
[[1 0 1 1]
 [0 1 0 0]
 [1 0 1 0]]


### Using Matrix

In [137]:
tem = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(tem)
print("__________")
print(nw_lst)
print("__________\n")


print(tem * nw_lst)
print("<><><><><><<><><><><><")
print(tem + nw_lst)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
__________
[[ 1  2  3 45]
 [ 4  5  6 78]
 [ 7  8  9 56]]
__________

[[  1   4   9 180]
 [ 20  30  42 624]
 [ 63  80  99 672]]
<><><><><><<><><><><><
[[ 2  4  6 49]
 [ 9 11 13 86]
 [16 18 20 68]]
